# Generated by Django 5.2.3 on 2025-06-23 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAE_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensor',
            new_name='Capteur',
        ),
        migrations.AlterModelOptions(
            name='data',
            options={},
        ),
        migrations.RenameField(
            model_name='capteur',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='timestamp',
            new_name='date_heure',
        ),
        migrations.RemoveField(
            model_name='data',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='data',
            name='value',
        ),
        migrations.AddField(
            model_name='data',
            name='id_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAE_app.capteur'),
        ),
    ]
