# Generated by Django 5.2.3 on 2025-06-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAE_app', '0002_rename_sensor_capteur_alter_data_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
